Repository Broke-Brokers/Broke_BRokers-soen341projectF2023, pull requests merged in 2023-11, with the labels that each got.

#250 Search-broker-search-language-isa
  package-lock.json
  package.json
  src/Pages/SearchForBrokers.js
  src/__tests__/__snapshots__/Search_Result_Grid.test.js.snap
  src/components/search-for-brokers/Search_Result_Grid.jsx
Labels: Merge Request, TASK, Test passed

#281 Offer_table
  src/Pages/Offer.js
  src/components/Offers/Offers_table.css
  src/components/Offers/Offers_table.jsx
Labels: TASK, Testing

#302 explaining firebase crash
  Sprint #3/Firebase Database/New database (after Firebase crash)/readme.md
Labels: documentation

#300 Update Sprint3_IsabelleCharles_ContributionLog
  Sprint #3/Member's contribution/Sprint3_IsabelleCharles_ContributionLog
Labels: documentation

#301 Firebase-resolve-exceed-data-isabelle
  package-lock.json
  package.json
  src/App.js
  src/Pages/MakeOffer.js
  src/Pages/Offer.js
  src/components/Offers/Offers_table.jsx
  src/components/Profile-page/Admin_Brokers_Grid.jsx
  src/components/forms/offer_form.jsx
  src/components/search-for-brokers/Search_Result_Grid.jsx
  src/firebase_configuration.js
Labels: bug, Datas, help wanted
